[package]
name = "broot"
version = "0.8.1"
authors = ["dystroy <denys.seguret@gmail.com>"]
repository = "https://github.com/Canop/broot"
description = "Fuzzy Search + tree + cd"
edition = "2018"
keywords = ["cli", "fuzzy", "tree", "search", "regex"]
license = "MIT"
categories = ["command-line-utilities"]
readme = "README.md"

[dependencies]
regex = "1"
lazy_static = "1.3"
directories = "2.0"
toml = "0.5"
custom_error = "1.6"
log = "0.4"
simplelog = "0.5"
clap = "2.32"
glob = "0.3"
crossbeam = "0.7"
opener = "0.4"
crossterm = "0.9.5"
termimad = "0.3.5"
#termimad = { path = "../termimad" }

[target.'cfg(unix)'.dependencies]
jemallocator = "0.3"
users = "0.9"

[profile.release]
lto = true # link time optimization - roughly halves the size of the exec
codegen-units = 1 # this removes a few hundred bytes from the final exec size
