[package]
name = "broot"
version = "0.2.3"
authors = ["Canop <cano.petrole@gmail.com>"]
edition = "2018"

[dependencies]
termion = "1.5.1"
regex = "1"
lazy_static = "1.2"
directories = "1.0"
toml = "0.4.9"
custom_error = "1.3.0"
log = "0.4"
simplelog = "0.5"
clap = "2.32"
