[package]
name = "broot"
version = "0.7.5"
authors = ["dystroy <denys.seguret@gmail.com>"]
repository = "https://github.com/Canop/broot"
description = "Fuzzy Search + tree + cd"
edition = "2018"
keywords = ["cli", "fuzzy", "tree", "search", "regex"]
license = "MIT"
categories = ["command-line-utilities"]
readme = "README.md"

[dependencies]
regex = "1"
lazy_static = "1.2"
directories = "1.0"
toml = "0.5"
custom_error = "1.6"
log = "0.4"
simplelog = "0.5"
clap = "2.32"
glob = "0.3"
jemallocator = "0.3"
crossbeam = "0.7"
opener = "0.3.2"
crossterm = "0.9.3"

[target.'cfg(unix)'.dependencies]
users = "0.9"

[profile.release]
lto = true
