[package]
name = "broot"
version = "0.9.4"
authors = ["dystroy <denys.seguret@gmail.com>"]
repository = "https://github.com/Canop/broot"
description = "Fuzzy Search + tree + cd"
edition = "2018"
keywords = ["cli", "fuzzy", "tree", "search", "regex"]
license = "MIT"
categories = ["command-line-utilities"]
readme = "README.md"

[dependencies]
chrono = "0.4"
regex = "1.3"
lazy_static = "1.4"
directories = "2.0"
toml = "0.5"
custom_error = "1.6"
log = "0.4"
simplelog = "0.6"
clap = "2.33"
glob = "0.3"
crossbeam = "0.7"
opener = "0.4"
crossterm_cursor = "=0.2.4"
crossterm_input = "=0.3.6"
crossterm_screen = "=0.2.3"
crossterm_style = "=0.3.3"
crossterm_terminal = "=0.2.4"
crossterm_utils = "=0.2.3"
umask = "0.1.4"
termimad = "0.6.5"
#termimad = { path = "../termimad" }

[target.'cfg(unix)'.dependencies]
users = "0.9"

[target.'cfg(windows)'.dependencies]
is_executable = "0.1"

[profile.release]
lto = true # link time optimization - roughly halves the size of the exec
codegen-units = 1 # this removes a few hundred bytes from the final exec size
