[package]
name = "btree"
version = "0.1.0"
authors = ["Canop <cano.petrole@gmail.com>"]

[dependencies]
termion = "1.5.1"
regex = "1"
lazy_static = "1.2"
directories = "1.0"
toml = "0.4.9"
custom_error = "1.3.0"
